AllCops:
  Include:
    - Rakefile

Metrics/LineLength:
  Max: 120
  Exclude:
    - flag-icons-rails.gemspec

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: leading

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FileName:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - test/**/*
